/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as StartRouteImport } from './routes/start'
import { Route as ActivatePublicSlugRouteImport } from './routes/activate.$publicSlug'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBatchesRouteImport } from './routes/admin/batches'
import { Route as AdminCasesRouteImport } from './routes/admin/cases'
import { Route as AdminFundRouteImport } from './routes/admin/fund'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminRewardCatalogRouteImport } from './routes/admin/reward-catalog'
import { Route as AdminRewardRulesRouteImport } from './routes/admin/reward-rules'
import { Route as AdminRiskRouteImport } from './routes/admin/risk'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthEmailRouteImport } from './routes/auth/email'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as PartnerIndexRouteImport } from './routes/partner/index'
import { Route as PartnerCampaignsRouteImport } from './routes/partner/campaigns'
import { Route as PartnerLoginRouteImport } from './routes/partner/login'
import { Route as PartnerRedemptionsRouteImport } from './routes/partner/redemptions'
import { Route as ReturnCaseTokenRouteImport } from './routes/return.$caseToken'
import { Route as RewardClaimTokenRouteImport } from './routes/reward.$claimToken'
import { Route as TransferTokenRouteImport } from './routes/transfer.$token'
import { Route as AppItemsIndexRouteImport } from './routes/app/items/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppProfileNotificationsRouteImport } from './routes/app/profile/notifications'
import { Route as AppReportsIndexRouteImport } from './routes/app/reports/index'
import { Route as AppReportsCaseNumberRouteImport } from './routes/app/reports/$caseNumber'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth/callback.$provider'
import { Route as TPublicSlugIndexRouteImport } from './routes/t/$publicSlug/index'
import { Route as TPublicSlugFoundRouteImport } from './routes/t/$publicSlug/found'
import { Route as TPublicSlugLocationRouteImport } from './routes/t/$publicSlug/location'
import { Route as TPublicSlugMessageRouteImport } from './routes/t/$publicSlug/message'
import { Route as TPublicSlugReportIssueRouteImport } from './routes/t/$publicSlug/report-issue'
import { Route as TPublicSlugSafetyRouteImport } from './routes/t/$publicSlug/safety'
import { Route as AppItemsIdIndexRouteImport } from './routes/app/items/$id/index'
import { Route as AppItemsIdActivityRouteImport } from './routes/app/items/$id/activity'
import { Route as AppItemsIdContactsRouteImport } from './routes/app/items/$id/contacts'
import { Route as AppItemsIdDeleteRouteImport } from './routes/app/items/$id/delete'
import { Route as AppItemsIdLostRouteImport } from './routes/app/items/$id/lost'
import { Route as AppItemsIdTransferRouteImport } from './routes/app/items/$id/transfer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivatePublicSlugRoute = ActivatePublicSlugRouteImport.update({
  id: '/activate/$publicSlug',
  path: '/activate/$publicSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFundRoute = AdminFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardCatalogRoute = AdminRewardCatalogRouteImport.update({
  id: '/reward-catalog',
  path: '/reward-catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardRulesRoute = AdminRewardRulesRouteImport.update({
  id: '/reward-rules',
  path: '/reward-rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiskRoute = AdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailRoute = AuthEmailRouteImport.update({
  id: '/auth/email',
  path: '/auth/email',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerCampaignsRoute = PartnerCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerRedemptionsRoute = PartnerRedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => PartnerRoute,
} as any)
const ReturnCaseTokenRoute = ReturnCaseTokenRouteImport.update({
  id: '/return/$caseToken',
  path: '/return/$caseToken',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardClaimTokenRoute = RewardClaimTokenRouteImport.update({
  id: '/reward/$claimToken',
  path: '/reward/$claimToken',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferTokenRoute = TransferTokenRouteImport.update({
  id: '/transfer/$token',
  path: '/transfer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppItemsIndexRoute = AppItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileNotificationsRoute = AppProfileNotificationsRouteImport.update({
  id: '/profile/notifications',
  path: '/profile/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCaseNumberRoute = AppReportsCaseNumberRouteImport.update({
  id: '/reports/$caseNumber',
  path: '/reports/$caseNumber',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const TPublicSlugIndexRoute = TPublicSlugIndexRouteImport.update({
  id: '/t/$publicSlug/',
  path: '/t/$publicSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TPublicSlugFoundRoute = TPublicSlugFoundRouteImport.update({
  id: '/t/$publicSlug/found',
  path: '/t/$publicSlug/found',
  getParentRoute: () => rootRouteImport,
} as any)
const TPublicSlugLocationRoute = TPublicSlugLocationRouteImport.update({
  id: '/t/$publicSlug/location',
  path: '/t/$publicSlug/location',
  getParentRoute: () => rootRouteImport,
} as any)
const TPublicSlugMessageRoute = TPublicSlugMessageRouteImport.update({
  id: '/t/$publicSlug/message',
  path: '/t/$publicSlug/message',
  getParentRoute: () => rootRouteImport,
} as any)
const TPublicSlugReportIssueRoute = TPublicSlugReportIssueRouteImport.update({
  id: '/t/$publicSlug/report-issue',
  path: '/t/$publicSlug/report-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const TPublicSlugSafetyRoute = TPublicSlugSafetyRouteImport.update({
  id: '/t/$publicSlug/safety',
  path: '/t/$publicSlug/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AppItemsIdIndexRoute = AppItemsIdIndexRouteImport.update({
  id: '/items/$id/',
  path: '/items/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsIdActivityRoute = AppItemsIdActivityRouteImport.update({
  id: '/items/$id/activity',
  path: '/items/$id/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsIdContactsRoute = AppItemsIdContactsRouteImport.update({
  id: '/items/$id/contacts',
  path: '/items/$id/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsIdDeleteRoute = AppItemsIdDeleteRouteImport.update({
  id: '/items/$id/delete',
  path: '/items/$id/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsIdLostRoute = AppItemsIdLostRouteImport.update({
  id: '/items/$id/lost',
  path: '/items/$id/lost',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsIdTransferRoute = AppItemsIdTransferRouteImport.update({
  id: '/items/$id/transfer',
  path: '/items/$id/transfer',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/partner': typeof PartnerRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/scan': typeof ScanRoute
  '/start': typeof StartRoute
  '/activate/$publicSlug': typeof ActivatePublicSlugRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/fund': typeof AdminFundRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/reward-catalog': typeof AdminRewardCatalogRoute
  '/admin/reward-rules': typeof AdminRewardRulesRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/email': typeof AuthEmailRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/partner/campaigns': typeof PartnerCampaignsRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/redemptions': typeof PartnerRedemptionsRoute
  '/return/$caseToken': typeof ReturnCaseTokenRoute
  '/reward/$claimToken': typeof RewardClaimTokenRoute
  '/transfer/$token': typeof TransferTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/app/profile/notifications': typeof AppProfileNotificationsRoute
  '/app/reports/$caseNumber': typeof AppReportsCaseNumberRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/t/$publicSlug/found': typeof TPublicSlugFoundRoute
  '/t/$publicSlug/location': typeof TPublicSlugLocationRoute
  '/t/$publicSlug/message': typeof TPublicSlugMessageRoute
  '/t/$publicSlug/report-issue': typeof TPublicSlugReportIssueRoute
  '/t/$publicSlug/safety': typeof TPublicSlugSafetyRoute
  '/app/items/': typeof AppItemsIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/t/$publicSlug/': typeof TPublicSlugIndexRoute
  '/app/items/$id/activity': typeof AppItemsIdActivityRoute
  '/app/items/$id/contacts': typeof AppItemsIdContactsRoute
  '/app/items/$id/delete': typeof AppItemsIdDeleteRoute
  '/app/items/$id/lost': typeof AppItemsIdLostRoute
  '/app/items/$id/transfer': typeof AppItemsIdTransferRoute
  '/app/items/$id/': typeof AppItemsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/permissions': typeof PermissionsRoute
  '/scan': typeof ScanRoute
  '/start': typeof StartRoute
  '/activate/$publicSlug': typeof ActivatePublicSlugRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/fund': typeof AdminFundRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/reward-catalog': typeof AdminRewardCatalogRoute
  '/admin/reward-rules': typeof AdminRewardRulesRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/email': typeof AuthEmailRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/partner/campaigns': typeof PartnerCampaignsRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/redemptions': typeof PartnerRedemptionsRoute
  '/return/$caseToken': typeof ReturnCaseTokenRoute
  '/reward/$claimToken': typeof RewardClaimTokenRoute
  '/transfer/$token': typeof TransferTokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/app/profile/notifications': typeof AppProfileNotificationsRoute
  '/app/reports/$caseNumber': typeof AppReportsCaseNumberRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/t/$publicSlug/found': typeof TPublicSlugFoundRoute
  '/t/$publicSlug/location': typeof TPublicSlugLocationRoute
  '/t/$publicSlug/message': typeof TPublicSlugMessageRoute
  '/t/$publicSlug/report-issue': typeof TPublicSlugReportIssueRoute
  '/t/$publicSlug/safety': typeof TPublicSlugSafetyRoute
  '/app/items': typeof AppItemsIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/t/$publicSlug': typeof TPublicSlugIndexRoute
  '/app/items/$id/activity': typeof AppItemsIdActivityRoute
  '/app/items/$id/contacts': typeof AppItemsIdContactsRoute
  '/app/items/$id/delete': typeof AppItemsIdDeleteRoute
  '/app/items/$id/lost': typeof AppItemsIdLostRoute
  '/app/items/$id/transfer': typeof AppItemsIdTransferRoute
  '/app/items/$id': typeof AppItemsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/partner': typeof PartnerRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/scan': typeof ScanRoute
  '/start': typeof StartRoute
  '/activate/$publicSlug': typeof ActivatePublicSlugRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/fund': typeof AdminFundRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/reward-catalog': typeof AdminRewardCatalogRoute
  '/admin/reward-rules': typeof AdminRewardRulesRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/email': typeof AuthEmailRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/partner/campaigns': typeof PartnerCampaignsRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/redemptions': typeof PartnerRedemptionsRoute
  '/return/$caseToken': typeof ReturnCaseTokenRoute
  '/reward/$claimToken': typeof RewardClaimTokenRoute
  '/transfer/$token': typeof TransferTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/app/profile/notifications': typeof AppProfileNotificationsRoute
  '/app/reports/$caseNumber': typeof AppReportsCaseNumberRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/t/$publicSlug/found': typeof TPublicSlugFoundRoute
  '/t/$publicSlug/location': typeof TPublicSlugLocationRoute
  '/t/$publicSlug/message': typeof TPublicSlugMessageRoute
  '/t/$publicSlug/report-issue': typeof TPublicSlugReportIssueRoute
  '/t/$publicSlug/safety': typeof TPublicSlugSafetyRoute
  '/app/items/': typeof AppItemsIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/t/$publicSlug/': typeof TPublicSlugIndexRoute
  '/app/items/$id/activity': typeof AppItemsIdActivityRoute
  '/app/items/$id/contacts': typeof AppItemsIdContactsRoute
  '/app/items/$id/delete': typeof AppItemsIdDeleteRoute
  '/app/items/$id/lost': typeof AppItemsIdLostRoute
  '/app/items/$id/transfer': typeof AppItemsIdTransferRoute
  '/app/items/$id/': typeof AppItemsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/help'
    | '/partner'
    | '/permissions'
    | '/scan'
    | '/start'
    | '/activate/$publicSlug'
    | '/admin/audit'
    | '/admin/batches'
    | '/admin/cases'
    | '/admin/fund'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/reward-catalog'
    | '/admin/reward-rules'
    | '/admin/risk'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/email'
    | '/onboarding/$step'
    | '/partner/campaigns'
    | '/partner/login'
    | '/partner/redemptions'
    | '/return/$caseToken'
    | '/reward/$claimToken'
    | '/transfer/$token'
    | '/admin/'
    | '/app/'
    | '/auth/'
    | '/partner/'
    | '/app/profile/notifications'
    | '/app/reports/$caseNumber'
    | '/auth/callback/$provider'
    | '/t/$publicSlug/found'
    | '/t/$publicSlug/location'
    | '/t/$publicSlug/message'
    | '/t/$publicSlug/report-issue'
    | '/t/$publicSlug/safety'
    | '/app/items/'
    | '/app/profile/'
    | '/app/reports/'
    | '/t/$publicSlug/'
    | '/app/items/$id/activity'
    | '/app/items/$id/contacts'
    | '/app/items/$id/delete'
    | '/app/items/$id/lost'
    | '/app/items/$id/transfer'
    | '/app/items/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/permissions'
    | '/scan'
    | '/start'
    | '/activate/$publicSlug'
    | '/admin/audit'
    | '/admin/batches'
    | '/admin/cases'
    | '/admin/fund'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/reward-catalog'
    | '/admin/reward-rules'
    | '/admin/risk'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/email'
    | '/onboarding/$step'
    | '/partner/campaigns'
    | '/partner/login'
    | '/partner/redemptions'
    | '/return/$caseToken'
    | '/reward/$claimToken'
    | '/transfer/$token'
    | '/admin'
    | '/app'
    | '/auth'
    | '/partner'
    | '/app/profile/notifications'
    | '/app/reports/$caseNumber'
    | '/auth/callback/$provider'
    | '/t/$publicSlug/found'
    | '/t/$publicSlug/location'
    | '/t/$publicSlug/message'
    | '/t/$publicSlug/report-issue'
    | '/t/$publicSlug/safety'
    | '/app/items'
    | '/app/profile'
    | '/app/reports'
    | '/t/$publicSlug'
    | '/app/items/$id/activity'
    | '/app/items/$id/contacts'
    | '/app/items/$id/delete'
    | '/app/items/$id/lost'
    | '/app/items/$id/transfer'
    | '/app/items/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/help'
    | '/partner'
    | '/permissions'
    | '/scan'
    | '/start'
    | '/activate/$publicSlug'
    | '/admin/audit'
    | '/admin/batches'
    | '/admin/cases'
    | '/admin/fund'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/reward-catalog'
    | '/admin/reward-rules'
    | '/admin/risk'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/email'
    | '/onboarding/$step'
    | '/partner/campaigns'
    | '/partner/login'
    | '/partner/redemptions'
    | '/return/$caseToken'
    | '/reward/$claimToken'
    | '/transfer/$token'
    | '/admin/'
    | '/app/'
    | '/auth/'
    | '/partner/'
    | '/app/profile/notifications'
    | '/app/reports/$caseNumber'
    | '/auth/callback/$provider'
    | '/t/$publicSlug/found'
    | '/t/$publicSlug/location'
    | '/t/$publicSlug/message'
    | '/t/$publicSlug/report-issue'
    | '/t/$publicSlug/safety'
    | '/app/items/'
    | '/app/profile/'
    | '/app/reports/'
    | '/t/$publicSlug/'
    | '/app/items/$id/activity'
    | '/app/items/$id/contacts'
    | '/app/items/$id/delete'
    | '/app/items/$id/lost'
    | '/app/items/$id/transfer'
    | '/app/items/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  HelpRoute: typeof HelpRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PermissionsRoute: typeof PermissionsRoute
  ScanRoute: typeof ScanRoute
  StartRoute: typeof StartRoute
  ActivatePublicSlugRoute: typeof ActivatePublicSlugRoute
  AuthEmailRoute: typeof AuthEmailRoute
  OnboardingStepRoute: typeof OnboardingStepRoute
  ReturnCaseTokenRoute: typeof ReturnCaseTokenRoute
  RewardClaimTokenRoute: typeof RewardClaimTokenRoute
  TransferTokenRoute: typeof TransferTokenRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
  TPublicSlugFoundRoute: typeof TPublicSlugFoundRoute
  TPublicSlugLocationRoute: typeof TPublicSlugLocationRoute
  TPublicSlugMessageRoute: typeof TPublicSlugMessageRoute
  TPublicSlugReportIssueRoute: typeof TPublicSlugReportIssueRoute
  TPublicSlugSafetyRoute: typeof TPublicSlugSafetyRoute
  TPublicSlugIndexRoute: typeof TPublicSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate/$publicSlug': {
      id: '/activate/$publicSlug'
      path: '/activate/$publicSlug'
      fullPath: '/activate/$publicSlug'
      preLoaderRoute: typeof ActivatePublicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fund': {
      id: '/admin/fund'
      path: '/fund'
      fullPath: '/admin/fund'
      preLoaderRoute: typeof AdminFundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reward-catalog': {
      id: '/admin/reward-catalog'
      path: '/reward-catalog'
      fullPath: '/admin/reward-catalog'
      preLoaderRoute: typeof AdminRewardCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reward-rules': {
      id: '/admin/reward-rules'
      path: '/reward-rules'
      fullPath: '/admin/reward-rules'
      preLoaderRoute: typeof AdminRewardRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/risk': {
      id: '/admin/risk'
      path: '/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AdminRiskRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email': {
      id: '/auth/email'
      path: '/auth/email'
      fullPath: '/auth/email'
      preLoaderRoute: typeof AuthEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/campaigns': {
      id: '/partner/campaigns'
      path: '/campaigns'
      fullPath: '/partner/campaigns'
      preLoaderRoute: typeof PartnerCampaignsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/login': {
      id: '/partner/login'
      path: '/login'
      fullPath: '/partner/login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/redemptions': {
      id: '/partner/redemptions'
      path: '/redemptions'
      fullPath: '/partner/redemptions'
      preLoaderRoute: typeof PartnerRedemptionsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/return/$caseToken': {
      id: '/return/$caseToken'
      path: '/return/$caseToken'
      fullPath: '/return/$caseToken'
      preLoaderRoute: typeof ReturnCaseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reward/$claimToken': {
      id: '/reward/$claimToken'
      path: '/reward/$claimToken'
      fullPath: '/reward/$claimToken'
      preLoaderRoute: typeof RewardClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer/$token': {
      id: '/transfer/$token'
      path: '/transfer/$token'
      fullPath: '/transfer/$token'
      preLoaderRoute: typeof TransferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/items/': {
      id: '/app/items/'
      path: '/items'
      fullPath: '/app/items/'
      preLoaderRoute: typeof AppItemsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/notifications': {
      id: '/app/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/app/profile/notifications'
      preLoaderRoute: typeof AppProfileNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/$caseNumber': {
      id: '/app/reports/$caseNumber'
      path: '/reports/$caseNumber'
      fullPath: '/app/reports/$caseNumber'
      preLoaderRoute: typeof AppReportsCaseNumberRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$publicSlug/': {
      id: '/t/$publicSlug/'
      path: '/t/$publicSlug'
      fullPath: '/t/$publicSlug/'
      preLoaderRoute: typeof TPublicSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$publicSlug/found': {
      id: '/t/$publicSlug/found'
      path: '/t/$publicSlug/found'
      fullPath: '/t/$publicSlug/found'
      preLoaderRoute: typeof TPublicSlugFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$publicSlug/location': {
      id: '/t/$publicSlug/location'
      path: '/t/$publicSlug/location'
      fullPath: '/t/$publicSlug/location'
      preLoaderRoute: typeof TPublicSlugLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$publicSlug/message': {
      id: '/t/$publicSlug/message'
      path: '/t/$publicSlug/message'
      fullPath: '/t/$publicSlug/message'
      preLoaderRoute: typeof TPublicSlugMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$publicSlug/report-issue': {
      id: '/t/$publicSlug/report-issue'
      path: '/t/$publicSlug/report-issue'
      fullPath: '/t/$publicSlug/report-issue'
      preLoaderRoute: typeof TPublicSlugReportIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$publicSlug/safety': {
      id: '/t/$publicSlug/safety'
      path: '/t/$publicSlug/safety'
      fullPath: '/t/$publicSlug/safety'
      preLoaderRoute: typeof TPublicSlugSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/items/$id/': {
      id: '/app/items/$id/'
      path: '/items/$id'
      fullPath: '/app/items/$id/'
      preLoaderRoute: typeof AppItemsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/items/$id/activity': {
      id: '/app/items/$id/activity'
      path: '/items/$id/activity'
      fullPath: '/app/items/$id/activity'
      preLoaderRoute: typeof AppItemsIdActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/items/$id/contacts': {
      id: '/app/items/$id/contacts'
      path: '/items/$id/contacts'
      fullPath: '/app/items/$id/contacts'
      preLoaderRoute: typeof AppItemsIdContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/items/$id/delete': {
      id: '/app/items/$id/delete'
      path: '/items/$id/delete'
      fullPath: '/app/items/$id/delete'
      preLoaderRoute: typeof AppItemsIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/items/$id/lost': {
      id: '/app/items/$id/lost'
      path: '/items/$id/lost'
      fullPath: '/app/items/$id/lost'
      preLoaderRoute: typeof AppItemsIdLostRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/items/$id/transfer': {
      id: '/app/items/$id/transfer'
      path: '/items/$id/transfer'
      fullPath: '/app/items/$id/transfer'
      preLoaderRoute: typeof AppItemsIdTransferRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBatchesRoute: typeof AdminBatchesRoute
  AdminCasesRoute: typeof AdminCasesRoute
  AdminFundRoute: typeof AdminFundRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminRewardCatalogRoute: typeof AdminRewardCatalogRoute
  AdminRewardRulesRoute: typeof AdminRewardRulesRoute
  AdminRiskRoute: typeof AdminRiskRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBatchesRoute: AdminBatchesRoute,
  AdminCasesRoute: AdminCasesRoute,
  AdminFundRoute: AdminFundRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminRewardCatalogRoute: AdminRewardCatalogRoute,
  AdminRewardRulesRoute: AdminRewardRulesRoute,
  AdminRiskRoute: AdminRiskRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProfileNotificationsRoute: typeof AppProfileNotificationsRoute
  AppReportsCaseNumberRoute: typeof AppReportsCaseNumberRoute
  AppItemsIndexRoute: typeof AppItemsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppItemsIdActivityRoute: typeof AppItemsIdActivityRoute
  AppItemsIdContactsRoute: typeof AppItemsIdContactsRoute
  AppItemsIdDeleteRoute: typeof AppItemsIdDeleteRoute
  AppItemsIdLostRoute: typeof AppItemsIdLostRoute
  AppItemsIdTransferRoute: typeof AppItemsIdTransferRoute
  AppItemsIdIndexRoute: typeof AppItemsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProfileNotificationsRoute: AppProfileNotificationsRoute,
  AppReportsCaseNumberRoute: AppReportsCaseNumberRoute,
  AppItemsIndexRoute: AppItemsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppItemsIdActivityRoute: AppItemsIdActivityRoute,
  AppItemsIdContactsRoute: AppItemsIdContactsRoute,
  AppItemsIdDeleteRoute: AppItemsIdDeleteRoute,
  AppItemsIdLostRoute: AppItemsIdLostRoute,
  AppItemsIdTransferRoute: AppItemsIdTransferRoute,
  AppItemsIdIndexRoute: AppItemsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PartnerRouteChildren {
  PartnerCampaignsRoute: typeof PartnerCampaignsRoute
  PartnerLoginRoute: typeof PartnerLoginRoute
  PartnerRedemptionsRoute: typeof PartnerRedemptionsRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerCampaignsRoute: PartnerCampaignsRoute,
  PartnerLoginRoute: PartnerLoginRoute,
  PartnerRedemptionsRoute: PartnerRedemptionsRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  HelpRoute: HelpRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PermissionsRoute: PermissionsRoute,
  ScanRoute: ScanRoute,
  StartRoute: StartRoute,
  ActivatePublicSlugRoute: ActivatePublicSlugRoute,
  AuthEmailRoute: AuthEmailRoute,
  OnboardingStepRoute: OnboardingStepRoute,
  ReturnCaseTokenRoute: ReturnCaseTokenRoute,
  RewardClaimTokenRoute: RewardClaimTokenRoute,
  TransferTokenRoute: TransferTokenRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
  TPublicSlugFoundRoute: TPublicSlugFoundRoute,
  TPublicSlugLocationRoute: TPublicSlugLocationRoute,
  TPublicSlugMessageRoute: TPublicSlugMessageRoute,
  TPublicSlugReportIssueRoute: TPublicSlugReportIssueRoute,
  TPublicSlugSafetyRoute: TPublicSlugSafetyRoute,
  TPublicSlugIndexRoute: TPublicSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
